travis:
  secure:
    BINSTAR_TOKEN: CcZwB+xCyBk7nMXDv5XdVlifiFRsmA8wVKt2iqkzM1YLeEAdc9/x5qI480bLcHxoemIgFpl2oi6vfmG2vtS2MMHrvxmx7+CINFa1ZRGf0Gf/df/0vZhqNL/va97SoNwoA3lkdBub3ETeuCUbiY7Pm8xfXLOZ1iA+XI0xw7LJSKRoSCT9mrNZHI3GIGdJL+/9m7ooMtzf/XFfmJvBTGvptEg717RWjUIXUU3QtaxxrMYwMPnKMLs1160/uy24B/q+dlm2uCHvAiHaees9RxV2G1ADtlv3dxJGvKQ+elIlN5M2nX05eVPmoVk+E7/WBgZWmaVPamj33OJhibKhwQYnlY/bVw9agBF57nHsc8RZP8jBmAOPqeIljm0a7mwYIwztgtDaOjeRb0Q7TbuRGkhcR1gvwrEmeOk83zu+RrGrYOs888R32CR0rsJxx3dlfMaIeqMUfSEf3rrMgCqCfLUVACupU3XKNddJHvoH0Up1AHqmBJNFsnD+sLBwpAILPMEKPS+1YkOOSFgGj0HkVUlZ769xCVLcF/ydGU97If4kqHpp3QYKLSxkxSlppW/4I9psST6iAPvRnrhZTeuUOx9BmwD2DAcqqLnVgp2Of1veIDfGpDnnbPPDaAaQ/G34XukklddHpb/lqf/gCVi51Kq2p6ZvbDvFsjsCsQ8koEbPSnw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
